run:
  tests: false
linters:
  enable-all: true
  disable:
    - forbidigo
    - stylecheck
    - gochecknoinits
    - gosec
    - revive
    - gochecknoglobals
    - exhaustivestruct
    - golint
    - ineffassign
    - staticcheck
    - wsl
    - gofumpt  
issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
      - gosec
      - forbidigo
      - golint
      - gochecknoinits
      - stylecheck
      - staticcheck
      - wsl
      text: "G107,ST1003"
